### ISSUE TITLE
Doesnt work with blender 4.0.1

### ISSUE THREAD

**Issue by DragonTheFolf** [SomeKitten/LegendsArceusBlenderScript#8]
attempting to load a model gives me the following error:
```
Python: Traceback (most recent call last):
  File "C:\Users\dragon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\PokemonSwitch.py", line 93, in execute
    from_trmdlsv(directory, f, self.rare, self.loadlods, self.bonestructh)
  File "C:\Users\dragon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\PokemonSwitch.py", line 473, in from_trmdlsv
    new_bone.use_inherit_scale = True
AttributeError: 'EditBone' object has no attribute 'use_inherit_scale'

```
